import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

List<String> province_th = [
  'กรุงเทพมหานคร',
  'กระบี่',
  'กาญจนบุรี',
  'กาฬสินธุ์',
  'กำแพงเพชร',
  'ขอนแก่น',
  'จันทบุรี',
  'ฉะเชิงเทรา',
  'ชลบุรี',
  'ชัยนาท',
  'ชัยภูมิ',
  'ชุมพร',
  'เชียงใหม่',
  'เชียงราย',
  'ตรัง',
  'ตราด',
  'ตาก',
  'นครนายก',
  'นครปฐม',
  'นครพนม',
  'นครราชสีมา',
  'นครศรีธรรมราช',
  'นครสวรรค์',
  'นนทบุรี',
  'นราธิวาส',
  'น่าน',
  'บึงกาฬ',
  'บุรีรัมย์',
  'ปทุมธานี',
  'ประจวบคีรีขันธ์',
  'ปราจีนบุรี',
  'ปัตตานี',
  'พระนครศรีอยุธยา',
  'พะเยา',
  'พังงา',
  'พัทลุง',
  'พิจิตร',
  'พิษณุโลก',
  'เพชรบุรี',
  'เพชรบูรณ์',
  'แพร่',
  'ภูเก็ต',
  'มหาสารคาม',
  'มุกดาหาร',
  'แม่ฮ่องสอน',
  'ยโสธร',
  'ยะลา',
  'ร้อยเอ็ด',
  'ระนอง',
  'ระยอง',
  'ราชบุรี',
  'ลพบุรี',
  'ลำปาง',
  'ลำพูน',
  'เลย',
  'ศรีสะเกษ',
  'สกลนคร',
  'สงขลา',
  'สตูล',
  'สมุทรปราการ',
  'สมุทรสงคราม',
  'สมุทรสาคร',
  'สระแก้ว',
  'สระบุรี',
  'สิงห์บุรี',
  'สุโขทัย',
  'สุพรรณบุรี',
  'สุราษฎร์ธานี',
  'สุรินทร์',
  'หนองคาย',
  'หนองบัวลำภู',
  'อ่างทอง',
  'อำนาจเจริญ',
  'อุดรธานี',
  'อุตรดิตถ์',
  'อุทัยธานี',
  'อุบลราชธานี',
];

List<dynamic> jsonData = [];
List<String> tempAddress = [];

Future<void> readJson() async {
  try {
    String jsonString = await rootBundle.loadString('assets/location.json');
    List<dynamic> data = jsonDecode(jsonString);
    tempAddress = [];
    jsonData = data;
    debugPrint(jsonData.toString());
  } catch (e) {
    print('Error reading JSON file: $e');
  }
}

Future<void> filterDistrict(String address) async {
  await readJson(); // Wait for JSON data to be loaded and parsed
  List<dynamic> filteredData =
      jsonData.where((item) => item['province'] == address).toList();
  filteredData.forEach((item) => tempAddress.add(item['district']));
  debugPrint(tempAddress.toString());
}

class Autogenerated {
  String? district;
  String? amphoe;
  String? province;
  int? zipcode;
  int? districtCode;
  int? amphoeCode;
  int? provinceCode;

  Autogenerated(
      {this.district,
      this.amphoe,
      this.province,
      this.zipcode,
      this.districtCode,
      this.amphoeCode,
      this.provinceCode});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    district = json['district'];
    amphoe = json['amphoe'];
    province = json['province'];
    zipcode = json['zipcode'];
    districtCode = json['district_code'];
    amphoeCode = json['amphoe_code'];
    provinceCode = json['province_code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['district'] = this.district;
    data['amphoe'] = this.amphoe;
    data['province'] = this.province;
    data['zipcode'] = this.zipcode;
    data['district_code'] = this.districtCode;
    data['amphoe_code'] = this.amphoeCode;
    data['province_code'] = this.provinceCode;
    return data;
  }
}