name: barter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.6

  #Utilities
  camera: ^0.10.5+9 # https://pub.dev/packages/camera/
  pinput: ^4.0.0 # https://pub.dev/packages/pinput
  flutter_switch: ^0.3.2 # https://pub.dev/packages/flutter_switch
  lottie: ^2.7.0 # https://pub.dev/packages/lottie
  introduction_screen: ^3.1.12 # https://pub.dev/packages/introduction_screen/
  persistent_bottom_nav_bar: ^5.0.2 # https://pub.dev/packages/persistent_bottom_nav_bar
  iconsax: ^0.0.8 # https://pub.dev/packages/iconsax
  carousel_slider: ^4.2.1 # https://pub.dev/packages/carousel_slider/
  infinite_scroll_pagination: ^4.0.0 # https://pub.dev/packages/infinite_scroll_pagination/
  intl: ^0.17.0
  google_fonts: ^6.2.1 # https://pub.dev/packages/google_font
  image_picker: ^1.0.8 # https://pub.dev/packages/image_picker/
  path_provider: ^2.1.3 # https://pub.dev/packages/path_provider
  font_awesome_flutter: ^10.7.0 #https://pub.dev/packages/font_awesome_flutter/
  dropdown_search: ^5.0.6 # https://pub.dev/packages/dropdown_search/

  #Local storage
  shared_preferences: ^2.2.2 # https://pub.dev/packages/shared_preferences

  # App icon
  flutter_launcher_icons: ^0.13.1 # https://pub.dev/packages/flutter_launcher_icons/

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/location.json
    - assets/introduction/
    - assets/banner/
    - assets/icons/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Italic.ttf
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
